// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5ogYlHPE8ehKuHpDWqxrjJ10omeE21ds',
    appId: '1:191698003540:web:56669d3d99cd114c0befc1',
    messagingSenderId: '191698003540',
    projectId: 'moviq-1cbf7',
    authDomain: 'moviq-1cbf7.firebaseapp.com',
    storageBucket: 'moviq-1cbf7.firebasestorage.app',
    measurementId: 'G-WFELLGCHDY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFaZZvxik-UmKzEtzo2A0XYT0Cn_IEaXM',
    appId: '1:191698003540:android:c0620122b1d00f8f0befc1',
    messagingSenderId: '191698003540',
    projectId: 'moviq-1cbf7',
    storageBucket: 'moviq-1cbf7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3TsPffPFpzGGJspd8MOhrTlz2T04B6bU',
    appId: '1:191698003540:ios:f2f268f20d6d5e7e0befc1',
    messagingSenderId: '191698003540',
    projectId: 'moviq-1cbf7',
    storageBucket: 'moviq-1cbf7.firebasestorage.app',
    iosClientId: '191698003540-3k0vslrvngsug9mntmungqph4hvbgije.apps.googleusercontent.com',
    iosBundleId: 'com.example.moviq',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3TsPffPFpzGGJspd8MOhrTlz2T04B6bU',
    appId: '1:191698003540:ios:f2f268f20d6d5e7e0befc1',
    messagingSenderId: '191698003540',
    projectId: 'moviq-1cbf7',
    storageBucket: 'moviq-1cbf7.firebasestorage.app',
    iosClientId: '191698003540-3k0vslrvngsug9mntmungqph4hvbgije.apps.googleusercontent.com',
    iosBundleId: 'com.example.moviq',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5ogYlHPE8ehKuHpDWqxrjJ10omeE21ds',
    appId: '1:191698003540:web:e4c507e552343fab0befc1',
    messagingSenderId: '191698003540',
    projectId: 'moviq-1cbf7',
    authDomain: 'moviq-1cbf7.firebaseapp.com',
    storageBucket: 'moviq-1cbf7.firebasestorage.app',
    measurementId: 'G-3MTF2CF61F',
  );

}